
[build]
  base    = "frontend/"
  command = "echo $NPM_FLAGS && npm build" 
  publish = "frontend/build"

[build.environment]

  NPM_FLAGS = "--ignore-optional --frozen-lockfile --network-timeout 1000000 --network-concurrency 1 --verbose"


[redirects]
  from = "/*"
  to = "/index.html"
  status = 200
  command = "CI= npm run build"

  [headers]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"